export {
  SLIME_BODY_WIDTH_M,
  SLIME_GROGGY_SCALE_Y,
  SLIME_GROGGY_STAR_FADE_S,
  SLIME_GROGGY_STAR_MIN_SCALE,
  SLIME_GROGGY_STRETCH,
  SLIME_GROGGY_TILT_RAD,
  SLIME_MIN_SURFACE_AREA_M2,
  SLIME_PATROL_SPEED_MPS,
  SLIME_SQUISH_STRETCH,
  SLIME_STAR_COUNT,
  SLIME_STAR_HEIGHT_M,
  SLIME_STAR_RADIUS_M,
  SLIME_STAR_SPIN_RAD_S,
  SLIME_STUN_DURATION_S,
  SLIME_SQUISH_SCALE_Y,
  SLIME_ZONE_HEIGHT_M,
  SLIME_ZONE_PAD_M,
} from './constants';
export {
  canExplorerPassSlime,
  createSlimeRuntime,
  explorerInSlimePatrolZone,
  isSlimeAwake,
  isSlimeGroggy,
  slimeBodyScaleY,
  slimePatrolConfig,
  slimeStarScale,
  slimeStarsVisible,
  stunSlime,
  tickSlime,
  writePatrolLocalOffset,
  writeSlimeBodyScale,
  writeStarPose,
} from './patrol';
export type {
  SlimeBodyScale,
  SlimeExplorerLocal,
  SlimePatrolAxis,
  SlimePatrolConfig,
  SlimeRuntime,
  SlimeStarPose,
  SlimeTickResult,
} from './types';
